### ISSUE TITLE
Support gzipped responses

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integrations#107]
Seen in production is the below response. The `Content-Encoding: gzip` response header is present. The HTTP client isn't properly decoding the gzipped body and that's why we see the garbled response body. 

The [generateHandle](https://github.com/activeprospect/leadconduit-integrations/blob/1eb8f43d5994331ec6564d10b46daf2543fff311/src/index.coffee#L149) function should look for the `gzip` value in the `Accept-Encoding` header. If it's present include the `gzip: true` option when making the request. This will automatically decompress the response body.

```
HTTP/1.1 400 Bad Request
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/json; charset=utf-8
Expires: -1
Server: Microsoft-IIS/7.5
X-Aspnet-Version: 4.0.30319
X-Powered-By: ASP.NET
X-Iinfo: 3-60424690-60424697 SNNN RT(1504111249706 919) q(0 0 0 7) r(1 1) U5
X-Cdn: Incapsula
X-Robots-Tag: noindex, nofollow
Content-Encoding: gzip
Date: Wed, 30 Aug 2017 16:40:50 GMT
Connection: close
Set-Cookie: ["visid_incap_1030307=ksiyjOS/StGHbEYZZMkYxJHqplkAAAAAQUIPAAAAAAD/lOnoi2I/AsSYc5r9wRkP; expires=Thu, 30 Aug 2018 08:00:51 GMT; path=/; Domain=.x.incapdns.net","incap_ses_168_1030307=E0xyHvNtmA70QtkT4ttUApLqplkAAAAA0GaH3EMuFzZMH5QErzyRig==; path=/; Domain=.x.incapdns.net"]
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization, Locale,Cache-Control,Accept-Language
Access-Control-Allow-Origin: *
 ��%��
�@Ee��¤�]���)��M؇��B���Ycy.�sVp�:��&z��t̑��c��-
����cj��2�
�QS�E3-�b�����p'��-����b؞H”���~��b�1H��{M]��X҈�tCv�T����r� �
```

**Comment by chasingSublimity** [comment]
This has been implemented (many moons ago). We don't use Issues anymore, but closing so the historical data doesn't come back and confuse someone. Like me. just now. :)
