### ISSUE TITLE
Pixel tracking integration

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integrations#20]

**Comment by alexj** [comment]
Alex, could you provide some detail on what you think is needed here? Is this simply a URL to hit when a step is reached, or is there more to it?

**Comment by alexkwolfe** [comment]
I think that's mostly it. 

* Make a GET request to a URL
* Follow redirects (?)
* Confirm that the response contains an image (?)

**Comment by cgrayson** [comment]
[Done](https://github.com/activeprospect/leadconduit-integration-pixeltracker).
