### ISSUE TITLE
Generic Postback Tracking

### ISSUE THREAD

**Issue by alexj** [activeprospect/leadconduit-integrations#36]
This integration should be pretty straightforward, as we will take a transaction ID passed by the source and include it on an outbound URL:

1. Flow creator adds this integration as a step in the flow and defines the postback URL: http://example.com/trackingpage?transaction_id={placeholder}
2. The inbound transaction_id is mapped to the postback (outbound) transaction_id
3. A lead comes in with a predefined transaction ID in the URL: http://example.com/?transaction_id=12345 and makes it to the appropriate step in the flow
4. LC hits the postback URL, using the tracking_id from the inbound URL in place of the placeholder
5. LC records the response from the postback server (Success / Failure), so action can be taken depending on the result. HasOffers returns `success=true;` when a transaction ID is valid, is still an active session, and hasn’t already been fired.

Here's a good explanation of how Postback tracking works on HasOffers: http://support.hasoffers.com/hc/en-us/articles/203338487-Postback-Tracking

We still need to get the proper posting URL.

**Comment by alexkwolfe** [comment]
How is this different from the pixel integration?

**Comment by alexj** [comment]
I've modified this to be specific to HasOffers. In time, we may add a generic PostBack, which will be very similar to the pixel integration, but we're not going to do so now.

**Comment by ros3bud** [comment]
Any luck in getting the proper posting URL? I'd like to start testing that out.

**Comment by alexj** [comment]
I think the HasOffers URL will be different per customer/offer: http://support.hasoffers.com/hc/en-us/articles/202325756-Global-Postback-URLs Please let me know if you understand differently after looking at the article. I'm also happy to help sketch out how to implement this, if it would be useful.
