### ISSUE TITLE
failing test for derived package name

### ISSUE THREAD

**Issue by cgrayson** [activeprospect/leadconduit-integrations#90]
As @jgrayson676 found: 

> [This test](https://github.com/activeprospect/leadconduit-integrations/blob/master/spec/modules-spec.coffee#L26) now fails after [this update](https://github.com/activeprospect/leadconduit-integration-default/pull/33/files). 

@alexkwolfe, you indicated in Slack that all modules will eventually get explicit names. What's your recommendation for this test: change to test a different module? Test the explicit name?

**Comment by alexkwolfe** [comment]
Why didn't this damned thing close on its own?!
