### ISSUE TITLE
new inbound: ADT "XML"

### ISSUE THREAD

**Issue by cgrayson** [activeprospect/leadconduit-integrations#91]
[This is DA-RT](https://github.com/activeprospect/deliveryadapter-realtime), and according to my research today, there is one single adapter that's been used in the last 6 days: ADT's. It translates encoded XML, posted in the parameter called `xml`, into a standard Classic lead post. 

This is that adapter (the DA-RT readme explains this somewhat): 

```json
{
  "_id": "4cd06e1d2fc9abe4a8c73f3a",
  "request": {
    "body": "{{body.xml | xpath: '//quoteList/quote/quoter/personalInfo/firstName/text()' | params: 'first_name'}}&{{body.xml | xpath: '//quoteList/quote/quoter/personalInfo/lastName/text()' | params: 'last_name'}}&{{body.xml | xpath: '//quoteList/quote/quoter/contactInfo/address/street/text()' | params: 'address1'}}&{{body.xml | xpath: '//quoteList/quote/quoter/contactInfo/address/city/text()' | params: 'city'}}&{{body.xml | xpath: '//quoteList/quote/quoter/contactInfo/address/state/stateAbbreviation/text()' | params: 'state'}}&{{body.xml | xpath: '//quoteList/quote/quoter/contactInfo/address/zip/text()' | params: 'postal_code'}}&{{body.xml | xpath: '//quoteList/quote/quoter/contactInfo/phone/numericPhone/text()' | params: 'phone_primary'}}&{{body.xml | xpath: '//quoteList/quote/quoter/contactInfo/email/emailAddress/text()' | params: 'email'}}",
    "query": "{{body | without: 'xml' | params}}",
    "method": "post",
    "header": {
      "content_type": "application/x-www-form-urlencoded"
    }
  },
  "response": {
    "body": "{%if body.response.result.__content__ == 'success'%}<?xml version='1.0' encoding='UTF-8'?><status><result>success</result></status>{% else %}<?xml version='1.0' encoding='UTF-8'?><status><result>{{raw_body | xpath: '//response/reason/text()' | join: ', '}} (lead id: {{body.response.leadId.__content__}})</result></status>{% endif %}",
    "header": {
      "content_type": "application/xml"
    }
  }
}
```

The essence is that the `request.body` is being created with data mapped like:

```
{{body.xml | xpath: '//quoteList/quote/quoter/personalInfo/firstName/text()' | params: 'first_name'}}&
{{body.xml | xpath: '//quoteList/quote/quoter/personalInfo/lastName/text()' | params: 'last_name'}}&
{{body.xml | xpath: '//quoteList/quote/quoter/contactInfo/address/street/text()' | params: 'address1'}}&
{{body.xml | xpath: '//quoteList/quote/quoter/contactInfo/address/city/text()' | params: 'city'}}&
{{body.xml | xpath: '//quoteList/quote/quoter/contactInfo/address/state/stateAbbreviation/text()' | params: 'state'}}&
{{body.xml | xpath: '//quoteList/quote/quoter/contactInfo/address/zip/text()' | params: 'postal_code'}}&
{{body.xml | xpath: '//quoteList/quote/quoter/contactInfo/phone/numericPhone/text()' | params: 'phone_primary'}}&
{{body.xml | xpath: '//quoteList/quote/quoter/contactInfo/email/emailAddress/text()' | params: 'email'}}
```

E.g. (turning that XPath syntax into JSON notation): `first_name=#{quoteList.quote.quoter.personalInfo.firstName}&last_name=#{quoteList.quote.quoter.personalInfo.lastName}&address1=…` 

And here is an example request: 

```
{
  "request_id": "056",
  "headers": {
    "content_type": "application/x-www-form-urlencoded",
    "referrer": null,
    "referer": null
  },
  "raw_body": " [**removed by me for this example because it's way long**] "
  "body": {
    "xxAccountId": "000rqltbb",
    "xxCampaignId": "051etuxg9",
    "dnis": "1117774444",
    "xml": "<quoteList><quote><quoteId>13434009</quoteId><categoryName>Access Control Systems</categoryName><categoryId>10056</categoryId><quoter><contactInfo><address><street>2073 Bear View Blvd</street><city>Finglewood</city><state><stateName>Florida</stateName><stateAbbreviation>FL</stateAbbreviation></state><zip>34993</zip></address><phone><phoneFreeText>5125551212</phoneFreeText><numericPhone>5125551212</numericPhone></phone><email><emailAddress>elizabeth@wolfrealtyinc.com</emailAddress></email></contactInfo><personalInfo><firstName>Elizabeth</firstName><lastName>Queen</lastName><fullName>Elizabeth Queen</fullName></personalInfo><businessInfo><companyName>Wolf Realty Rentals</companyName><title>General Manager</title><industry>Real Estate</industry></businessInfo></quoter><requestDetails><questionWithAnswers><question>Number of users:</question><answer>100-499</answer><priorityLevel>0</priorityLevel></questionWithAnswers><questionWithAnswers><question>Number of doors:</question><answer>1-4</answer><priorityLevel>0</priorityLevel></questionWithAnswers><questionWithAnswers><question>Install:</question><answer>Yes</answer><priorityLevel>0</priorityLevel></questionWithAnswers><questionWithAnswers><question>Square footage:</question><answer>2,500 - 4,999 sq. ft.</answer><priorityLevel>0</priorityLevel></questionWithAnswers><questionWithAnswers><question>Purchasing timeframe:</question><answer>In two months or more</answer><priorityLevel>0</priorityLevel></questionWithAnswers><questionWithAnswers><question>Zip code:</question><answer>34223</answer><priorityLevel>0</priorityLevel></questionWithAnswers><questionWithAnswers><question>Email address:</question><answer>elizabeth@wolfrealtyinc.com</answer><priorityLevel>0</priorityLevel></questionWithAnswers></requestDetails></quote></quoteList>"
  },
  "ip": "54.164.5.2",
  "adapter_id": "4cd06e1d2fc9abe4a8c73f3a",
  "type": "request",
  "method": "POST",
  "url": {
    "full": "http://app.leadconduit.com/v2/PostLeadAction",
    "query": {},
    "scheme": "http",
    "host": "app.leadconduit.com",
    "full_query": "",
    "full_path": "/v2/PostLeadAction",
    "port": 80,
    "path": [
      "v2",
      "PostLeadAction"
    ]
  }
}
```

This integration should create leads with: 

- `campaign_id` from `xxCampaignId`
- `campaign_sub_id_1` from `xxAccountId`
- `reference` from `dnis`
- `first_name` from  '//quoteList/quote/quoter/personalInfo/firstName'
- `last_name` from '//quoteList/quote/quoter/personalInfo/lastName'
- `address_1` from '//quoteList/quote/quoter/contactInfo/address/street'
- `city` from '//quoteList/quote/quoter/contactInfo/address/city'
- `state` from //quoteList/quote/quoter/contactInfo/address/state/stateAbbreviation'
- `postal_code` from '//quoteList/quote/quoter/contactInfo/address/zip'
- `phone_1` from '//quoteList/quote/quoter/contactInfo/phone/numericPhone/'
- `email` from '//quoteList/quote/quoter/contactInfo/email/emailAddress'

And it should give a response (based on the [Liquid template](https://shopify.github.io/liquid/) in the adapter above), as follows.

On success:

```xml
<?xml version='1.0' encoding='UTF-8'?><status><result>success</result></status>
```
Otherwise:

```xml
<?xml version='1.0' encoding='UTF-8'?><status><result>#{reason} (lead id: #{classic.lead_id or lead.id})</result></status>
```
Note the lead id returned in the non-success response should try to use a Classic id if present; this integration will surely be used with a Classic recipient (though I'm not sure that's the right variable name in that example).

**Comment by alexkwolfe** [comment]
I'm pretty sure this is a BuyerZone request.

**Comment by cgrayson** [comment]
Ok. They're all going to one of two ADT campaigns.

**Comment by alexkwolfe** [comment]
Do those campaigns have the source listed as BuyerZone? I'm asking these questions because it's sort of annoying that ADT can't use a standard BuyerZone source with the standard (but currently non existent) Access Control Systems inbound integration.

**Comment by cgrayson** [comment]
They don't have a BuyerZone source in these LCC campaigns (there's one in their account, with 0 shared campaigns & no volume). 

It is a little annoying, but less so to me, partly because Access Control Systems is non-existent :smiley: and partly because this isn't sending anything but contact data, anyway. 

In case it wasn't clear, I think that if we build this (rather simple) integration, we can shut down DA-RT.

**Comment by alexkwolfe** [comment]
Shutting down DART would be great. Who does ADT show as the source of these leads?

**Comment by cgrayson** [comment]
You know what, this is getting weirder the more I look at it. These leads are indeed all getting posted to Classic with the Buyerzone source id (`000rqltbb`), but that source isn't valid in either campaign (or any campaigns) and shows zero flow. BUT those leads are somehow succeeding, and they're getting attributed to a totally different source (Zeta Interactive, id `054edq2zy`). What the actual eff.

Ha ha, _wow_. The data in `LEAD_PATH` is hosed. There are two rows, one's inactive, and the other's active, the latter is hooked for some reason to the Zeta entity. Not even sure what to do about that, but anyway. 

:yak:

Your answer: the source _is_ actually Buyerzone! Kind of! But not really! :persevere:
